<a href="https://colab.research.google.com/github/Birunthaban/FlightPricePrediction-ML/blob/main/model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

In [2]:
url = "https://github.com/Birunthaban/FlightPricePrediction-ML/blob/main/Data_Train.xlsx?raw=true"
df= pd.read_excel(url)

In [3]:
df.head(10)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

## Shuffle the data

In [5]:
shuffled_df = shuffle(df, random_state=42)

In [6]:
shuffled_df.head(10)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
6076,Jet Airways,18/05/2019,Kolkata,Banglore,CCU → BOM → BLR,05:45,18:15,12h 30m,1 stop,In-flight meal not included,10844
3544,GoAir,3/06/2019,Delhi,Cochin,DEL → BOM → COK,10:35,19:35,9h,1 stop,No info,4959
7313,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → BOM → BLR,14:05,19:50,5h 45m,1 stop,No info,14781
5032,IndiGo,24/05/2019,Chennai,Kolkata,MAA → CCU,14:45,17:05,2h 20m,non-stop,No info,3858
2483,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,22:50,04:25 22 May,5h 35m,1 stop,In-flight meal not included,12898
9894,Multiple carriers,6/05/2019,Delhi,Cochin,DEL → BOM → COK,07:30,19:00,11h 30m,1 stop,No info,10529
346,Jet Airways,27/05/2019,Delhi,Cochin,DEL → BOM → COK,10:00,19:00,9h,1 stop,No info,16079
6366,Jet Airways,15/04/2019,Banglore,Delhi,BLR → DEL,19:50,22:50,3h,non-stop,No info,7229
8270,SpiceJet,21/06/2019,Chennai,Kolkata,MAA → CCU,17:45,20:05,2h 20m,non-stop,No info,3597
3393,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,19:00,11h,1 stop,No info,16289

In [7]:
df= shuffled_df

## drop duplicates

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.dropna(inplace=True)

## Splitting the data

In [10]:
X = df.drop(['Price'],axis=1)
y = df['Price']
X

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
6076,Jet Airways,18/05/2019,Kolkata,Banglore,CCU → BOM → BLR,05:45,18:15,12h 30m,1 stop,In-flight meal not included
3544,GoAir,3/06/2019,Delhi,Cochin,DEL → BOM → COK,10:35,19:35,9h,1 stop,No info
7313,Jet Airways,1/05/2019,Kolkata,Banglore,CCU → BOM → BLR,14:05,19:50,5h 45m,1 stop,No info
5032,IndiGo,24/05/2019,Chennai,Kolkata,MAA → CCU,14:45,17:05,2h 20m,non-stop,No info
2483,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,22:50,04:25 22 May,5h 35m,1 stop,In-flight meal not included
...,...,...,...,...,...,...,...,...,...,...
5734,Jet Airways,27/03/2019,Delhi,Cochin,DEL → BOM → COK,09:00,04:25 28 Mar,19h 25m,1 stop,No info
5191,Jet Airways,9/05/2019,Kolkata,Banglore,CCU → BOM → BLR,14:05,20:45,6h 40m,1 stop,In-flight meal not included
5390,Multiple carriers,15/05/2019,Delhi,Cochin,DEL → BOM → COK,12:50,01:30 16 May,12h 40m,1 stop,No info
860,IndiGo,03/03/2019,Banglore,New Delhi,BLR → DEL,00:40,03:25,2h 45m,non-stop,No info
7270,Jet Airways,1/06/2019,Delhi,Cochin,DEL → BOM → COK,13:00,04:25 02 Jun,15h 25m,1 stop,In-flight meal not included



#### Approach 1: Using Column Indexing
X = df[['feature1', 'feature2']]
y = df['label']

#### Approach 2: Using iloc (Index-Based Selection)
X = df.iloc[:, :-1]  # Select all columns except the last one (label)
y = df.iloc[:, -1]   # Select the last column (label)

#### Approach 3: Using loc (Label-Based Selection)
X = df.loc[:, ['feature1', 'feature2']]
y = df.loc[:, 'label']

#### Approach 4: Using drop (Dropping Columns)
X = df.drop('label', axis=1)
y = df['label']

#### Approach 5: Using pop (Extracting and Removing Column)
y = df.pop('label')  # 'label' column is extracted and removed from df
X = df

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,y,train_size=.85,random_state=0)

In [12]:
print(len(X_train))
print("\n")
print(len(y_train))

8892


8892

In [13]:
X_train.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64

Change Duration into one unit (minutes)

In [14]:
def changeDurationFormat(duration:str):
  result =duration.split()
  if len(result)==2:
    hours =int(duration.split()[0][0:-1])
    minutes = int(duration.split()[1][0:-1])
    return hours*60 + minutes
  else:
    if 'h' in result[0]:
      hours=int(result[0][0:-1])*60
      return hours
    else:
      minutes =int(result[0][0:-1])
      return minutes

In [15]:
def cleanDuration(data:pd.DataFrame):
  duration =data['Duration']
  return duration.apply(changeDurationFormat)

In [16]:
X_train['Duration'] = cleanDuration(X_train)

In [17]:
X_train

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
6157,Jet Airways,21/03/2019,Delhi,Cochin,DEL → BDQ → BOM → COK,10:45,04:25 22 Mar,1060,2 stops,No info
9561,IndiGo,1/04/2019,Banglore,Delhi,BLR → DEL,16:55,19:55,180,non-stop,No info
9433,Jet Airways,24/05/2019,Kolkata,Banglore,CCU → BOM → BLR,06:30,18:15,705,1 stop,No info
4509,IndiGo,1/06/2019,Chennai,Kolkata,MAA → CCU,05:15,07:40,145,non-stop,No info
8775,SpiceJet,24/06/2019,Mumbai,Hyderabad,BOM → HYD,13:15,14:45,90,non-stop,No check-in baggage included
...,...,...,...,...,...,...,...,...,...,...
10205,IndiGo,15/03/2019,Banglore,New Delhi,BLR → DEL,23:30,02:20 16 Mar,170,non-stop,No info
3590,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,10:00,19:00,540,1 stop,No info
8277,Multiple carriers,15/05/2019,Delhi,Cochin,DEL → BOM → COK,18:00,01:30 16 May,450,1 stop,No info
2703,GoAir,1/04/2019,Banglore,Delhi,BLR → DEL,07:45,10:40,175,non-stop,No info
57,Vistara,6/03/2019,Chennai,Kolkata,MAA → CCU,07:05,09:20,135,non-stop,No info